### ISSUE TITLE
Add guides / examples in the Readme

### ISSUE THREAD

**Issue by robinboening** [input-output-hk/cardano-js-sdk#1153]
### Describe the feature you'd like

It seems like this SDK is a very comprehensive collection of libraries. I'd love to get my hands dirty, but I am not an expert with JS and I struggle to understand how to get started with this SDK in the browser. I'd really appreciate some guides and examples to get started, like a simple wallet connect, building a simple transaction, signing a message, etc.

### Would you be willing to implement it?

- [ ] Yes, I will implement it.

**Comment by rhyslbw** [comment]
Closing in favour of using a [discussion](https://github.com/input-output-hk/cardano-js-sdk/discussions/519)
