### ISSUE TITLE
Installation and usage guide

### ISSUE THREAD

**Issue by 34r7h** [input-output-hk/cardano-js-sdk#128]
I know this is in heavy dev but please provide a guide to get started.

**Comment by rhyslbw** [comment]
Thanks for the interest in the product @34r7h, and I can understand your eagerness to use it, but there won't be much more done in the way of user guides until we solidify the APIs. We will be improving docs prior to the production release, but feel free to open a [discussion](https://github.com/input-output-hk/cardano-js-sdk/discussions) if you would like to ask any questions that may be of assistance.
