### ISSUE TITLE
Empty List Using Indefinite Encoding

### ISSUE THREAD

**Issue by EzePze** [input-output-hk/cardano-js-sdk#1318]
### Summary

When constructing an empty `PlutusList`, calling `toCbor` serialises it with indefinite encoding, which is not canonical and can cause problems with scripts, particularly the `serialise` builtin.

### Steps to reproduce the bug

```ts
console.log((new PlutusList()).toCbor())
console.log(PlutusList.fromCbor(HexBlob("80")).toCbor())
```

### Actual Result

```
9fff
9fff
```
Which is the encoding for an indefinite list

### Expected Result

```
80
80
```
Which is the encoding for a definite list

### SDK version

0.30.2

### Environment type

- [X] Node.js
- [ ] Browser
- [ ] Browser Extension
- [ ] Other

**Comment by AngelCastilloB** [comment]
Thanks for the bug report @EzePze, I opened a PR with the fix here https://github.com/input-output-hk/cardano-js-sdk/pull/1319, should be fixed in the next version of the SDK

**Comment by AngelCastilloB** [comment]
@EzePze we just published version 0.33.0 of the [@cardano-sdk/core](https://www.npmjs.com/package/@cardano-sdk/core) which should have this fixed, give it a try and let us know

**Comment by AngelCastilloB** [comment]
It seems that the issue was not properly fixed, see https://github.com/input-output-hk/cardano-js-sdk/pull/1319#issuecomment-2151584168 . Is being addressed in this PR https://github.com/input-output-hk/cardano-js-sdk/pull/1322

**Comment by AngelCastilloB** [comment]
You can try the latest release 0.33.1, that should have this fixed :)
