### ISSUE TITLE
getNetworkId missing from cip30 WalletApi type

### ISSUE THREAD

**Issue by Pagebakers** [input-output-hk/cardano-js-sdk#170]
WalletApi in the cip30 package is missing a method according to the spec.

`getNetworkId(): Promise<number>`

https://github.com/cardano-foundation/CIPs/tree/master/CIP-0030#apigetnetworkid-promisenumber

**Comment by rhyslbw** [comment]
Thanks for the report @Pagebakers, we've allocated development hours to bring this package up to the current version of the spec, so will close this gap soon.
