### ISSUE TITLE
Upgrade dependencies of cip30 package?

### ISSUE THREAD

**Issue by siegfried** [input-output-hk/cardano-js-sdk#194]
Failed to install the cip30 package.

```
yarn add @cardano-sdk/cip30
yarn add v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error @cardano-ogmios/client@4.1.0: The engine "node" is incompatible with this module. Expected version "^14". Got "17.4.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Or is it possible to use the types defined in this package without ogmois client?

**Comment by rhyslbw** [comment]
Thanks for the report. That's actually a dangling dependency, so we can remove it altogether. FYI this package is being worked on now in #192, so best to wait for this before considering integration.
