### ISSUE TITLE
cardano-wallet Provider integration

### ISSUE THREAD

**Issue by Sam-Jeston** [input-output-hk/cardano-js-sdk#25]
The re-write of the wallet backend is now at a point where we can start integrating with it as a Provider.

Our KeyManager interfaces will likely evolve through this process due to the differing behaviours of a traditional "light client API" compared to the implementation of `cardano-wallet`

**Comment by rhyslbw** [comment]
As we are doing with the KeyManager and CardanoPrimitive implementations, this should live in the `lib`. It's really a refactor of the `HttpProvider`

**Comment by rhyslbw** [comment]
#32
