### ISSUE TITLE
Should have provided an open source node?  and demo more particular demo...this is hard to user

### ISSUE THREAD

**Issue by lijianl** [input-output-hk/cardano-js-sdk#27]

**Comment by rhyslbw** [comment]
Hi @lijianl, thanks for having a look at the library. I've just updated the README, and added a preview of what's coming relating to a local Cardano network and API provider. Right now we're in active development, so watch this repo for updates.

https://github.com/input-output-hk/cardano-js-sdk/blob/develop/docs/setup_a_local_cardano_network_and_provider_using_docker.md
