### ISSUE TITLE
How to get UTXO? and Send Signed Transaction to cardano network without running local node or any Endpoint

### ISSUE THREAD

**Issue by rohitsahu21** [input-output-hk/cardano-js-sdk#38]

**Comment by Sam-Jeston** [comment]
Thanks for opening this @rohitsahu21 

This is not currently possible with the upstream APIs available to us. We expect this to change over the next few months.

I agree this is a valid use case, and once we have the upstream dependency to handle this, we'll implement this and will post on this issue then.
