### ISSUE TITLE
How to get Daedalus master key from Daedalus memo?

### ISSUE THREAD

**Issue by mmo2112** [input-output-hk/cardano-js-sdk#40]
Hi, I have Daedalus memo and I want to get master key from these memo to contact with Yoroi/wasp (for few reasons). Is there any method to get master key? The difference is between BIP39 vs 44 makes wrong while converting:
```
const cardano = require('cardano-wallet');
const dMemo = ...;
const dEntropy = cardano.Entropy.from_english_mnemonics(words);
const dWallet = cardano.DaedalusWallet.recover(dEntropy);
const privateKey = cardano.PrivateKey.new(dEntropy);
const pk = privateKey.to_hex();
console.log("pk", pk);
```
Thanks so much for help.

**Comment by SebastienGllmt** [comment]
This issue can be closed since it opened in the proper repository [here](https://github.com/input-output-hk/js-cardano-wasm/issues/76)

**Comment by Sam-Jeston** [comment]
Thanks @SebastienGllmt. Closed with the reference provided.
