### ISSUE TITLE
JavaScript client for browser

### ISSUE THREAD

**Issue by VOR73X** [input-output-hk/cardano-js-sdk#55]
For the mass adoption of Cardano I consider "cardano-js-sdk" fundamental for the creation of Web sites that communicate with the Cardano blockchain. Currently I see that it is Work In Progress, I would like to understand if this is currently the version, or are you working on another repository on a Javascript compatible client?

**Comment by rhyslbw** [comment]
Hi @VOR73X  thanks for raising the issue. This will be an area of focus after the upcoming protocol upgrade, and we certainly share your position on this.

**Comment by rhyslbw** [comment]
We have rebooted this product development, so stay tuned for upcoming releases.
