### ISSUE TITLE
how to sign cardano  offline 

### ISSUE THREAD

**Issue by benjamintshi** [input-output-hk/cardano-js-sdk#66]
i want to sign cardno ada offline ,and get rawTx .

**Comment by rhyslbw** [comment]
Hi @benjamintshi 

This repository is currently being updated to be compatible with the modern Cardano stack. In the mean-time you can use https://github.com/Emurgo/cardano-serialization-lib directly.

**Comment by benjamintshi** [comment]
@rhyslbw  Thanks.
