### ISSUE TITLE
Transaction Input Selection

### ISSUE THREAD

**Issue by Sam-Jeston** [input-output-hk/cardano-js-sdk#9]
Balance transaction logic is currently managed by the Wallet API, that has access to the key pairs.

I think it is viable to implement this client side. Let's create an implementation that we can take to people more familiar with the wallet API for review.

**Comment by Sam-Jeston** [comment]
Here is a great write-up. https://iohk.io/blog/self-organisation-in-coin-selection/

I see no issue in implementing the Random-Improve algorithm in our SDK. There will be network overhead for light clients, but this is unavoidable and the nature of the issue.

**Comment by rhyslbw** [comment]
Done in #20
