### ISSUE TITLE
Running demo fails (missing "typeorm-extension")

### ISSUE THREAD

**Issue by mcsherrylabs** [input-output-hk/cardano-js-sdk#942]
### Summary

Instling everything from scratch as described on the demo page fails 

` node demo/projection-typeorm.js`

result in ...

`Error: Cannot find module 'typeorm-extension'`

`npm -i typeorm-extension` fails but 

`yarn add typeorm-extension` seems to work...

### Steps to reproduce the bug

` node demo/projection-typeorm.js`

### Actual Result

`Error: Cannot find module 'typeorm-extension'`

### Expected Result

No error

### SDK version

0.4.1

### Environment type

- [X] Node.js
- [ ] Browser
- [ ] Browser Extension
- [ ] Other

### Environment details

Ubuntu

**Comment by rhyslbw** [comment]
Thanks for reporting @mcsherrylabs. We should have a `package.json` in the demo dir to handle this.

**Comment by rhyslbw** [comment]
As-of https://github.com/input-output-hk/cardano-js-sdk/commit/32d6992613a65e204a29bf9dfd576622a4d854b4 @mkazlauskas  replaced this demo with better documentation :star: 

- [Projection docs](https://github.com/input-output-hk/cardano-js-sdk/blob/master/packages/projection/README.md)
- [TypeORM Projection docs](https://github.com/input-output-hk/cardano-js-sdk/blob/master/packages/projection-typeorm/README.md)
